### ISSUE TITLE
Todo 2019-02-07 1:00 AM

### ISSUE THREAD

**Issue by Vilthsu** [Vilthsu/recipebook#8]
Todo-lista:

- [x] Reseptin poistaminen
- [x] Reseptin muokkaaminen
- [x] Reseptin raaka-aineet
- [ ] Kaikki reseptit -sivun pagination eli jakaminen usealle sivulle mikäli tuloksia on x määrä
- [x] Kirjoita dokumentaatiota
- [ ] (jos aikaa) Ryhmittely eri ryhmiin (makeat, suolaiset, pikareseptit (kestää alle x ajan), sesonki ... )
- [ ] (jos aikaa) Käyttäjän omat tiedot -sivu
- [ ] (jos aikaa) Valinnainen kuva reseptille
- [ ] (jos aikaa) Bootstrap kustomointi

**Comment by Vilthsu** [comment]
Reseptin kuva on toteutettu /recipes/<id> -osoitteessa, mutta käyttää toistaiseksi https://placeholder.com/ tarjoamia "placeholder image" -kuvia. Tulossa myös ominaisuus, jonka avulla voi lisätä oman kuvan joko URL:n tai file inputin avulla.

**Comment by Vilthsu** [comment]
Lisätty dokumentaatio, TODO:na tietokantakaavion päivitys.
